### ISSUE TITLE
Migrar para .py e Usar scipy.special.kl_div

### ISSUE THREAD

**Issue by storopoli** [RosalRicardo/metrica-citacao#1]
Sugiro trocar o formato Jupyter Notebook para um script Python que é muito melhor para versionamento e diffs.

Além disso, tem uma função no SciPy que calcula a K-L Divergence (e deve ser melhor otimizada que algo definido pelo usuário em NumPy): [`scipy.special.kl_div`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.special.kl_div.html).

PS: faça alguns benchmarks `%timeit` com a sua função do NumPy versus o `scipy.special.kl_div`

**Comment by RosalRicardo** [comment]
foi criado um modulo para as funções como uma `docstring` para documentar a função e um module de testes para comparar os tempos, resultou que a função com o numpy ficou mais rapida.

`tempo scipy: 0.006739599999999957`
`tempo manual: 0.004862499999999992`
`a funcao do scipy e mais eficiente em %: -0.3860359897172171`

**Comment by storopoli** [comment]
SciPy é bem ruim hein?

E se usássemos Julia?

`StatsBase.jl` tem KL-div: https://juliastats.org/StatsBase.jl/latest/scalarstats/#StatsBase.kldivergence

Além disso dá para usar density ratios: https://discourse.julialang.org/t/kullback-leibler-divergence-for-vector-and-normal-distribution/58246/5

**Comment by RosalRicardo** [comment]
feito o modulo em Julia, e rodei um benchmark com a macro @btime, aproximadamente 4 vezes mais rápido do que a função com melhor tempo no python! 

alem do fato que o uso dos pacotes `distributions` e usando unit ranges fica muito mais legível... muito legal mesmo.

obrigado pela sugestão.

**Comment by storopoli** [comment]
😂
